apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-realty-api
  namespace: mern-realty-dev
spec:
  template:
    spec:
      containers:
      - name: mern-realty-api
        image: famasboy888/mern-realty-api:1.1.8-dev.7415094
        envFrom:
          - secretRef:
              name: api-secrets
