resources:
  - ../../base
  - api/api-secret.yaml
  - client/client-secret.yaml
  - namespace.yaml
namespace: mern-realty-dev
images:
  #API
  - name: famasboy888/mern-realty-api
    newTag: 1.6.0-dev.13d2037
  #Client
  - name: famasboy888/mern-realty-client
    newTag: 1.4.0-dev.175b703
patches:
  # API
  - path: api/patch.yaml
    target:
      kind: Deployment
      name: mern-realty-api
  # Client
  - path: client/patch.yaml
    target:
      kind: Deployment
      name: mern-realty-client
  - path: client/client-service-patch.yaml
    target:
      kind: Service
      name: client-service
