resources:
- ../../base
- api/api-secret.yaml
- client/client-secret.yaml
- namespace.yaml

namespace: mern-realty-dev

images:
#API
- name: famasboy888/mern-realty-api
  newTag: 1.5.0-dev.ada2b90

#Client
- name: famasboy888/mern-realty-client
  newTag: 1.3.0-dev.ada2b90

patches:
# API
- path: api/patch.yaml
  target:
    kind: Deployment
    name: mern-realty-api

# Client
- path: client/patch.yaml
  target:
    kind: Deployment
    name: mern-realty-client

- path: client/client-service-patch.yaml
  target:
    kind: Service
    name: client-service
