apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-realty-client
  namespace: mern-realty-dev
spec:
  template:
    spec:
      containers:
      - name: mern-realty-client
        image: famasboy888/mern-realty-client:1.3.0-dev.ada2b90
        envFrom:
        - secretRef:
            name: client-secrets
