---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-secrets
  namespace: default
spec:
  encryptedData:
    VITE_GOOGLE_CLIENT_ID: AgBrz6F/3BV/q8bquFlpih6wWg3Hm2OJ/tULnxHb1TvePslpkV3bp69Ua1aBmKHWu9fXk64mKBBodeBO8JTt7Gdggpquz0JRPR+6PT5RIXVM2afoDBYMNS+61rthW33PcXhJpwFdZR2akFQMS8VxiR6I0dDb/mirVX0zkMtrvzAeQeAYnj6kkgUMAPbjLQFHY1sqA7IUgz8VoxXntONQ3nKdCt9Qs5vLN50rDG4Pc1a0dEOXMSfEUYR47DlGtDdFblOIDRTispEzqUpCHUKRuxeSqz+8kxUqDV1aSgX5WgyGyFEmS1Y4dsGH5kLbgyKIgIN4wDJT0HfpNUuNQMuo7UD0XOrEPJ1yOFbyabSc+liLS90/6NNeTLVX+sPK8fq/zqtqZoPaSew2lYRuqXvML6fw09F6ZRSFFrSrMH80Eq0C4mBADfiQkoJz84+0ssVgcZCSsPrTvzICP4UT1oiFVSNgVWgWW3F9gayV/wa10Dq/b4GctQ+W4262y9eJrFd/wyL/3Fx5OzeO/tzDg6mjtIc0cCVKY3WzyeI8bvEqVFg5i16oHYXdMdfsdD8oC7RpZQ9QRTBENU4Jez84DBZaOidJ987mpcg0lExR6lUd8APfpEGb/LSAYCqekPbef+hhAx3WwyghbNgGvI2PpmRDr3NK5FwAr2J5A4pZDOAaqt/h4W8oz7qAI2ruXcq9cB2kbWZ4RVmUlXSAc1emvG63kN1R2qxwWI8DSzighC/qOKYEkWkmOTJI1LHoJhI7Fq9IJdTn2dfZ/3onjQ61Z/ra6nde7QQZ65rrYEI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      creationTimestamp: null
      name: client-secrets
      namespace: default
