apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  selector:
    app: mern-realty-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
