---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: client-secrets
  namespace: mern-realty-staging
spec:
  encryptedData:
    VITE_GOOGLE_CLIENT_ID: AgBWvPbtlXWM8kF/ug6zBjmescbLZTocWHIZz5OK4T6dfypUmFJrrN2tzY7Ef7RtYGsbhFSOeWQS5x6ffAZya4H4WEeC9fms3ZVXtcCKl54R5AwqUMEAFJ3JHqUoiunpMAEAlDYd11NuuyVyEhF2N0G8+xb/0LOZ2Quq9C3Zn0gux2YVAT1oIrRQqQ8fFZ5N58egIL3WJM6hr8PZP0aQh5cetoNtt+bftXDbREstB+YOIdXFZmomyqqEg8tnXC3b9aGJ+X+7ivb62xPuJb2tNE2k1kkgdqDU50pqPDYfpa6sgTpynNXZYsNVX00jKxNO7knVDsUXCiQg9O7h8/C7spyGFBV+8TfLvC1P6izrnqoKy3/Sciq2bZkJqFjCw2os/RC+WMy7ZXZxQ1IW38SnPwYE+t1zRTuk2oj4R1mua1vsfTbYrtZjjN51OY1u36CL0d8FCQvbP1AlKc85b/bxJxnh5wTi3UZq9mD59oJzOFNcOb2xDXzDCr1V394AP4x/Td/wv1GToadrJQOFulQdd9mL4sNDRPBp6yowNd+nWSN5MV9Bs+dCyF0iWoAy4nfZWYsg3QI1VL5ll8Wk9FKgbbER6yHfOkclc9wp6MVDU/YoGdNL55MZjshGLs30sMFSHV69jYOK/DSwoSF83FrmsfYi1s2WvWJPGuOnNEt8Sy8gz0fl3z79vpbmAcytsvFL/Q78k3n+ARomcj9Zj90y8y6exVrYe1iAeFuM/XabWnKTaTqR2GZ8S20iUTrNGmSWq3Ps5KeP03FWiIQGsGTD7Fk/Go6ZmFIStSg=
    VITE_NODE_ENV: AgAAxin+X1SHpOgPomMESjMwDLQ0kbDa7Mw/V2e7cflkqQwqtT7XVuyMN62n6BmzkO52a+MXW+Z6vPxloxOGu001N4t8Fh8la7UPQi+qxIjNYQvJ70GIibTYFlF5EVr3W7h2dy+oqMTQtgp3xLFQe6mhbAstK8vtsV344/OH/vizjVZMp/4XdRTFR68vjzQI9GCqurlqi7H4Kl3fEsTG5lmsiH1zcKXnhTZFnOiofLSD2/rBHaFqsjEcK7tpni7Ek8fTQB7aosLlEeAJFX1qxmje/FdGZRWKUYzjJpobg1oEYGtlVWPyR6VPJNIbJRlGjiEYt7sLCzsS9CDy5SShZDonw0IAlzG6R4tAuscUs+gNzmfYosddz/MFOa6VaD5BE78IQwNJA/97m50eT9b9BzjilKXO2l0d9dxznXlZ10H9ROYSqbxFdFMuoWuWDU5fm6SlFJto61gmZGDSc/srSZJsLYkJKDZNptZqjjRi5QiioosuGzoiwgrBzGXp/rZ25j1drsH1SadkPOxafGhqFX5Njszc4JzaGFH4vOpJZMSQZuz0y/fMg8NaV5S4r19xpGl/c6r9BQoFqZPDU4nxr85Hree9mVMJxP1sHPMCbHBmXBTlwm0XcxYbOnDeWIlEieWtcbNbxGY2W5Ho2WP/bNCG+FV+n40jprw1Yd9Z9Mzqwo/k4oFw7cE84qHWYLTX6z4J16jRY+Nk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: client-secrets
      namespace: mern-realty-staging
    type: Opaque
